-- NVIDIA CUDA backends are deliberately isolated behind --nv-gpu=y.
target("llaisys-device-nvidia")
    set_kind("static")
    set_languages("cxx17")
    add_rules("cuda")
    add_cuflags("-Xcompiler=-fPIC", {force = true})
    add_files("../src/device/nvidia/*.cu")
    add_cugencodes("native")
    add_links("cudart")
    on_install(function (target) end)
target_end()

target("llaisys-ops-nvidia")
    set_kind("static")
    add_deps("llaisys-tensor")
    set_languages("cxx17")
    add_rules("cuda")
    add_cuflags("-Xcompiler=-fPIC", {force = true})
    add_files("../src/ops/*/nvidia/*.cu")
    add_cugencodes("native")
    add_links("cudart", "cublas")
    on_install(function (target) end)
target_end()
