[metadata]
name = llaisys
version = 0.1.0
description = Python APIs for llaisys
author = Pan Zezhong
license = MIT

[options]
packages = find:
include_package_data = True
zip_safe = False
install_requires =
    torch==2.2.2; sys_platform == "darwin" and platform_machine == "x86_64"
    torch>=2.4.0; sys_platform != "darwin" or platform_machine != "x86_64"
    numpy<2; sys_platform == "darwin" and platform_machine == "x86_64"
    transformers>=4.48,<5; sys_platform == "darwin" and platform_machine == "x86_64"
    transformers; sys_platform != "darwin" or platform_machine != "x86_64"
    accelerate

[options.package_data]
llaisys = 
    libllaisys/*.so
    libllaisys/*.dll
    libllaisys/*.dylib
